spring.application.name=SpringBootWebFlix
server.port=7793
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.r2dbc.url=r2dbc:mysql://localhost:3306/mlamarch
spring.r2dbc.username=root
spring.r2dbc.password=root@39

debug=true
#spring.jackson.deserialization.fail-on-null-for-primitives=false